<?php

/***************************************************************
<<<<<<< HEAD
 * Extension Manager/Repository config file for ext: "extbasepages"
 *
 * Auto generated by Extension Builder 2014-07-11
=======
 * Extension Manager/Repository config file for ext: "slimblog"
 *
 * Auto generated by Extension Builder 2014-07-15
>>>>>>> 2025ff3d9721d46a429a32ce0b1f6bf250d6d5dc
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Extbase Pages',
	'description' => 'Provides a page class for extbase.',
	'category' => 'plugin',
	'author' => 'Frederik Vosberg',
	'author_email' => 'frederik.vosberg@rattazonk.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
